# Generated by Django 5.1.6 on 2025-06-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=10)),
                ('num_years', models.IntegerField(default=0)),
                ('year1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year3_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year4_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year5_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year6_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year1_divisions', models.IntegerField(default=0)),
                ('year2_divisions', models.IntegerField(default=0)),
                ('year3_divisions', models.IntegerField(default=0)),
                ('year4_divisions', models.IntegerField(default=0)),
                ('year5_divisions', models.IntegerField(blank=True, default=0, null=True)),
                ('year6_divisions', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.CharField(max_length=6)),
                ('seating_capacity', models.IntegerField(default=0)),
                ('room_type', models.CharField(choices=[('class room', 'Class Room'), ('lab', 'Laboratory')], default='class room', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('total_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_number', models.CharField(max_length=10, unique=True)),
                ('course_name', models.CharField(max_length=40)),
                ('weekly_slots', models.IntegerField(default=0)),
                ('course_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], default='theory', max_length=10)),
                ('year', models.CharField(help_text='Year name (e.g. FE, SE, TE, BE)', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.department')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField()),
                ('division_number', models.IntegerField()),
                ('division_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.department')),
            ],
            options={
                'unique_together': {('department', 'year_number', 'division_number')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day', models.CharField(max_length=20)),
                ('time_slot', models.IntegerField()),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.division')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.room')),
            ],
            options={
                'unique_together': {('department', 'year', 'division', 'day', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(help_text='Year name (e.g. FE, SE, TE, BE)', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.division')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.instructor')),
            ],
            options={
                'unique_together': {('department', 'year', 'division', 'course', 'teacher')},
            },
        ),
    ]
